---
title: "prim_val_TLP12"
author: "Brecht Soulliaert"
date: "2025-09-10"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(R.utils)
library(xml2)
library(stringr)
library(dplyr)
library(ggpubr)
library(ggrepel)
```

```{r}
qpcr_res <- read_csv("../data/prim_val_res2.csv") %>%
  mutate(log2_concentration = log2(Concentration_attomoles_µl))
qpcr_res
```


```{r}
# Text label for correlations
# pearson_cor <- cor(qpcr_res$Cq, qpcr_res$log2_concentration, method = "pearson")
# spearman_cor <- cor(qpcr_res$Cq, qpcr_res$log2_concentration, method = "spearman")


pearson_test <- cor.test(qpcr_res$Cq,
                         qpcr_res$log2_concentration,
                         method = "pearson")

spearman_test <- cor.test(qpcr_res$Cq,
                         qpcr_res$log2_concentration,
                         method = "spearman")

pearson_cor <- pearson_test$estimate
pearson_pval <- pearson_test$p.value

spearman_cor <- spearman_test$estimate
spearman_pval <- spearman_test$p.value

```

```{r}
lims <- range(c(qpcr_res$Cq, qpcr_res$log2_concentration), na.rm = TRUE)

# corr_label <- sprintf("Pearson r= %.2f\nSpearman r=%.2f",
#                       pearson_cor, spearman_cor)
corr_label <- sprintf(
  "Pearson:  %.2f  p = %.2e\nSpearman: %.2f  p = %.2e",
  pearson_cor, pearson_pval,
  spearman_cor, spearman_pval
)

pltv3<-ggplot(qpcr_res, aes(x = log2_concentration, y = Cq)) +
geom_point() +
    geom_smooth(method = "lm", color = "red", se = TRUE, alpha = 0.2) +
    geom_abline(intercept = 0, slope = -1, linetype = "dashed", 
                color = "gray40", linewidth = 0.7)+
  labs(x = "log2 concentration (attomoles/uL)", y = "Cq") +
  annotate("text",
           x = lims[1], y = lims[2],
           hjust = 0, vjust = 1,
           label = corr_label,
           size = 3.5) +
    theme_bw() +
    theme(
      plot.title = element_text(face = "bold", size = 12),
      axis.title = element_text(size = 10),
      strip.text = element_text(size = 9),
      panel.grid.minor = element_blank()
    )

pltv3

ggsave("../results/figures/ERCC_corr.pdf", pltv3, dpi=300, width = 8, height = 6)
```

